---
# tasks file for s3
  - name: Create directory
    remote_user: ubuntu
    file:                                                                                             
        path: "{{ item }}"
        state: directory
        mode: 0777
    with_items:
      - /home/$USER/wp-content
      - /home/$USER/db_data
  
  - name: change fuse.conf
    copy:
        src: ../../../fuse.conf
        dest: /etc/fuse.conf

  - name: Mount s3 to directory
    remote_user: ubuntu
    ansible.builtin.shell: s3fs -o iam_role=auto -o allow_other -o nonempty -o endpoint=eu-central-1 -o url="https://s3-eu-central-1.amazonaws.com" bruno-volume /home/$USER/wp-content
    args:
      executable: /bin/bash
